# The first folder that contains all obsidian files
# Use full path or relative path, but don't use ~/
obsidian_folder_path_str: 'C:\Users\00332659\OneDrive - Universidad San Francisco de Quito\Documentos\NotasCursos' 



# The note that will be used as the index.html 
# should be in obsidian_folder_path_str
# Use full path or relative path, but don't use ~/
obsidian_entrypoint_path_str: 'C:\Users\00332659\OneDrive - Universidad San Francisco de Quito\Documentos\NotasCursos\Notas CAPA.md'

html_output_folder_path_str: 'docs'


html_url_prefix: '/NotasCursos'


site_name: 'Notas de capa'

toggles:
  features:
    styling: 
      layout: documentation
    breadcrumbs:
      enabled: True
    table_of_contents: 
      add_toc_when_missing: True    # add "[TOC]" (Table of Contents) when missing  # if there is only one header, don't show the TOC

html_custom_inclusions:
  - '<link rel="stylesheet" href="custom.css" />'
  - '<style>
    .mjx-math {
        font-size: 18px; /* Adjust the size as needed */
    }
</style>'



file_exports:
  - encoding: binary
    src: css/custom.css
    dst: custom.css
  - encoding: binary
    src: fonts/LMMono8-Regular.woff
    dst: LMMono8-Regular.woff
  - encoding: binary
    src: fonts/LMMono8-Regular.woff2
    dst: LMMono8-Regular.woff2

navbar_links:
  - name: Home
    link: index.html
  - name: ¿Cómo usar este website?
    link: Guía para usar el website.html
  - name: Acerca del autor
    link: capa.html

 